version: '3'
services:
  redis-server:
    image: 'redis'
  strava-sync-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "8080:8080"
    volumes: 
      - ~/Documents/GIT/github_GrzegorzCzm/strava-sync-backend/src:/usr/app/src