version: '3'
services:
  redis-server:
    image: 'redis'
  strava-sync-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "8080:8080"
    volumes: 
      - ~/<PATH_TO_YOUR_PROJECT_FOLDER>/src:/usr/app/src