const testData = [
  {
    resource_state: 2,
    athlete: { resource_state: 2, firstname: "Jan", lastname: "S." },
    name: "Afternoon Walk",
    distance: 3119.8,
    moving_time: 2978,
    elapsed_time: 5444,
    total_elevation_gain: 42.1,
    type: "Walk",
  },
  {
    resource_state: 2,
    athlete: { resource_state: 2, firstname: "Jan", lastname: "S." },
    name: "Cape Naturaliste",
    distance: 16555.5,
    moving_time: 3004,
    elapsed_time: 3004,
    total_elevation_gain: 283,
    type: "VirtualRide",
  },
  {
    resource_state: 2,
    athlete: { resource_state: 2, firstname: "Jan", lastname: "S." },
    name: "Cow Creek",
    distance: 22363.3,
    moving_time: 2701,
    elapsed_time: 2720,
    total_elevation_gain: 77,
    type: "VirtualRide",
  },
  {
    resource_state: 2,
    athlete: { resource_state: 2, firstname: "Jan", lastname: "S." },
    name: "Tour of Slovenia | Ljubljana",
    distance: 17974.3,
    moving_time: 2824,
    elapsed_time: 2839,
    total_elevation_gain: 195,
    type: "VirtualRide",
  },
  {
    resource_state: 2,
    athlete: { resource_state: 2, firstname: "Jan", lastname: "S." },
    name: "Lava Beds NM",
    distance: 15942.6,
    moving_time: 2135,
    elapsed_time: 2175,
    total_elevation_gain: 122,
    type: "VirtualRide",
  },
  {
    resource_state: 2,
    athlete: { resource_state: 2, firstname: "Jan", lastname: "S." },
    name: "Alpenbrevet - Oberalppass",
    distance: 4743.8,
    moving_time: 1227,
    elapsed_time: 1480,
    total_elevation_gain: 138,
    type: "VirtualRide",
  },
  {
    resource_state: 2,
    athlete: {
      resource_state: 2,
      firstname: "Grzegorz",
      lastname: "C.",
    },
    name: "Dobre kilometry vol. 5",
    distance: 12866.6,
    moving_time: 4127,
    elapsed_time: 4169,
    total_elevation_gain: 8,
    type: "Run",
    workout_type: 0,
  },
  {
    resource_state: 2,
    athlete: {
      resource_state: 2,
      firstname: "Grzegorz",
      lastname: "C.",
    },
    name: "Dobre kilometry vol. 4",
    distance: 67416.5,
    moving_time: 9472,
    elapsed_time: 10016,
    total_elevation_gain: 195.2,
    type: "Ride",
    workout_type: 10,
  },
  {
    resource_state: 2,
    athlete: {
      resource_state: 2,
      firstname: "Grzegorz",
      lastname: "C.",
    },
    name: "Dobre kilometry - vol. 3",
    distance: 53207.1,
    moving_time: 7515,
    elapsed_time: 7745,
    total_elevation_gain: 142.5,
    type: "Ride",
    workout_type: 10,
  },
  {
    resource_state: 2,
    athlete: {
      resource_state: 2,
      firstname: "Grzegorz",
      lastname: "C.",
    },
    name: "Dobre kilometry - vol. II",
    distance: 43781.1,
    moving_time: 6669,
    elapsed_time: 6908,
    total_elevation_gain: 106.7,
    type: "Ride",
    workout_type: 10,
  },
  {
    resource_state: 2,
    athlete: {
      resource_state: 2,
      firstname: "Grzegorz",
      lastname: "C.",
    },
    name: "Klepiemy dobre kilometry ",
    distance: 15643.5,
    moving_time: 5103,
    elapsed_time: 5166,
    total_elevation_gain: 9.9,
    type: "Run",
    workout_type: 0,
  },
  {
    resource_state: 2,
    athlete: {
      resource_state: 2,
      firstname: "Grzegorz",
      lastname: "C.",
    },
    name: "Oblężnicze 15k",
    distance: 15772.2,
    moving_time: 5232,
    elapsed_time: 5629,
    total_elevation_gain: 14.5,
    type: "Run",
    workout_type: 0,
  },
  {
    resource_state: 2,
    athlete: {
      resource_state: 2,
      firstname: "Grzegorz",
      lastname: "C.",
    },
    name: "Kilogramy w dół, robić formę :)",
    distance: 6198.1,
    moving_time: 1877,
    elapsed_time: 1934,
    total_elevation_gain: 5.7,
    type: "Run",
    workout_type: 0,
  },
  {
    resource_state: 2,
    athlete: {
      resource_state: 2,
      firstname: "Grzegorz",
      lastname: "C.",
    },
    name: "Jak nie równomiernie to szarpanie, byle do przodu. ",
    distance: 11351.1,
    moving_time: 3839,
    elapsed_time: 3916,
    total_elevation_gain: 19.3,
    type: "Run",
    workout_type: 0,
  },
  {
    resource_state: 2,
    athlete: { resource_state: 2, firstname: "Jan", lastname: "S." },
    name: "Tour de Silesia 2020",
    distance: 100284,
    moving_time: 15327,
    elapsed_time: 19286,
    total_elevation_gain: 823.9,
    type: "Ride",
    workout_type: 11,
  },
  {
    resource_state: 2,
    athlete: {
      resource_state: 2,
      firstname: "Grzegorz",
      lastname: "C.",
    },
    name: "Pierwsze biegowe szczyty",
    distance: 11718.5,
    moving_time: 4671,
    elapsed_time: 5381,
    total_elevation_gain: 414.8,
    type: "Run",
    workout_type: 0,
  },
  {
    resource_state: 2,
    athlete: { resource_state: 2, firstname: "Jan", lastname: "S." },
    name: "Afternoon Ride",
    distance: 67648.9,
    moving_time: 11896,
    elapsed_time: 12187,
    total_elevation_gain: 540.6,
    type: "Ride",
    workout_type: 10,
  },
  {
    resource_state: 2,
    athlete: {
      resource_state: 2,
      firstname: "Grzegorz",
      lastname: "C.",
    },
    name: "Jest i uczciwe 10k++",
    distance: 10672.7,
    moving_time: 3384,
    elapsed_time: 3453,
    total_elevation_gain: 5.7,
    type: "Run",
    workout_type: 0,
  },
  {
    resource_state: 2,
    athlete: {
      resource_state: 2,
      firstname: "Grzegorz",
      lastname: "C.",
    },
    name: "Głodny biegu, głodny wybiegł, głodowo się skończyło",
    distance: 6246.9,
    moving_time: 2035,
    elapsed_time: 2071,
    total_elevation_gain: 5.7,
    type: "Run",
    workout_type: 0,
  },
  {
    resource_state: 2,
    athlete: {
      resource_state: 2,
      firstname: "Grzegorz",
      lastname: "C.",
    },
    name: "Spotkanie z sarną x 2",
    distance: 8199.5,
    moving_time: 2495,
    elapsed_time: 2541,
    total_elevation_gain: 5.7,
    type: "Run",
    workout_type: 0,
  },
  {
    resource_state: 2,
    athlete: {
      resource_state: 2,
      firstname: "Grzegorz",
      lastname: "C.",
    },
    name: "Powoli, powoli, byle dreptać kilometry ",
    distance: 8148.8,
    moving_time: 2626,
    elapsed_time: 2668,
    total_elevation_gain: 5.8,
    type: "Run",
    workout_type: 0,
  },
  {
    resource_state: 2,
    athlete: { resource_state: 2, firstname: "Jan", lastname: "S." },
    name: "Afternoon Ride",
    distance: 16224.5,
    moving_time: 5476,
    elapsed_time: 7219,
    total_elevation_gain: 212.5,
    type: "Ride",
    workout_type: 10,
  },
  {
    resource_state: 2,
    athlete: {
      resource_state: 2,
      firstname: "Grzegorz",
      lastname: "C.",
    },
    name: "Wydreptane nawet i trochę w deszczu. To już jestem PRO?",
    distance: 8337.6,
    moving_time: 2748,
    elapsed_time: 2797,
    total_elevation_gain: 7.6,
    type: "Run",
    workout_type: 0,
  },
  {
    resource_state: 2,
    athlete: {
      resource_state: 2,
      firstname: "Grzegorz",
      lastname: "C.",
    },
    name: "86 + chodnik = brak kolan",
    distance: 12662.6,
    moving_time: 4804,
    elapsed_time: 4889,
    total_elevation_gain: 19.9,
    type: "Run",
    workout_type: 0,
  },
  {
    resource_state: 2,
    athlete: { resource_state: 2, firstname: "Jan", lastname: "S." },
    name: "Afternoon Ride",
    distance: 59393.3,
    moving_time: 10204,
    elapsed_time: 10261,
    total_elevation_gain: 413.8,
    type: "Ride",
    workout_type: 10,
  },
  {
    resource_state: 2,
    athlete: {
      resource_state: 2,
      firstname: "Grzegorz",
      lastname: "C.",
    },
    name: "Trójka z przodu zobowiązuje",
    distance: 54660.8,
    moving_time: 6447,
    elapsed_time: 6447,
    total_elevation_gain: 144.8,
    type: "Ride",
    workout_type: 10,
  },
  {
    resource_state: 2,
    athlete: { resource_state: 2, firstname: "Jan", lastname: "S." },
    name: "Evening Ride",
    distance: 37964.4,
    moving_time: 7907,
    elapsed_time: 8077,
    total_elevation_gain: 435.1,
    type: "Ride",
    workout_type: 10,
  },
];

const testDataNew = [
  {
    resource_state: 2,
    athlete: {
      resource_state: 2,
      firstname: "Grzegorz",
      lastname: "C.",
    },
    name: "W świetle czołówki ",
    distance: 6332.2,
    moving_time: 1847,
    elapsed_time: 1884,
    total_elevation_gain: 5.6,
    type: "Run",
    workout_type: 0,
  },
  {
    resource_state: 2,
    athlete: {
      resource_state: 2,
      firstname: "Grzegorz",
      lastname: "C.",
    },
    name: "Łapiemy słońce",
    distance: 72036.3,
    moving_time: 10115,
    elapsed_time: 11182,
    total_elevation_gain: 208.7,
    type: "Ride",
    workout_type: 10,
  },
  {
    resource_state: 2,
    athlete: {
      resource_state: 2,
      firstname: "Grzegorz",
      lastname: "C.",
    },
    name: "Let’s run",
    distance: 6230.6,
    moving_time: 1816,
    elapsed_time: 1849,
    total_elevation_gain: 5.6,
    type: "Run",
    workout_type: 0,
  },
  {
    resource_state: 2,
    athlete: { resource_state: 2, firstname: "Jan", lastname: "S." },
    name: "Afternoon Walk",
    distance: 3119.8,
    moving_time: 2978,
    elapsed_time: 5444,
    total_elevation_gain: 42.1,
    type: "Walk",
  },
  {
    resource_state: 2,
    athlete: { resource_state: 2, firstname: "Jan", lastname: "S." },
    name: "Cape Naturaliste",
    distance: 16555.5,
    moving_time: 3004,
    elapsed_time: 3004,
    total_elevation_gain: 283,
    type: "VirtualRide",
  },
  {
    resource_state: 2,
    athlete: { resource_state: 2, firstname: "Jan", lastname: "S." },
    name: "Cow Creek",
    distance: 22363.3,
    moving_time: 2701,
    elapsed_time: 2720,
    total_elevation_gain: 77,
    type: "VirtualRide",
  },
  {
    resource_state: 2,
    athlete: { resource_state: 2, firstname: "Ja-n", lastname: "S." },
    name: "Tour of Slovenia | Ljubljana",
    distance: 17974.3,
    moving_time: 2824,
    elapsed_time: 2839,
    total_elevation_gain: 195,
    type: "VirtualRide",
  },
];

exports.testData = testData;
exports.testDataNew = testDataNew;
